### ISSUE TITLE
ubuntu-hideout.js.org

### ISSUE THREAD

**Issue by MattIPv4** [ByteCommander/ubuntu-hideout#4]
# JS.ORG CLEANUP
Hello, it seems a `js.org` subdomain that was requested to target this repository (or another on this user/organisation) no longer works.
The subdomain requested was `ubuntu-hideout.js.org` and had the target of `bytecommander.github.io/ubuntu-hideout`.
To keep the `js.org` subdomain you should add a page with [reasonable content](https://github.com/js-org/js.org/wiki/No-Content) within a month so the subdomain doesn't resolve to a 404 any longer.
Otherwise the requested subdomain will be removed from JS.ORGs zonefile and the list of active subdomains.

**If you are wanting to keep the `js.org` subdomain and have added [reasonable content](https://github.com/js-org/js.org/wiki/No-Content), YOU MUST reply to the [main cleanup issue](https://github.com/js-org/js.org/issues/2455) with the response format detailed at the top to keep the requested subdomain.**

**Comment by ByteCommander** [comment]
@MattIPv4 You say the site responded with 404, but this is not true, and should also not have ever been the case within the last weeks, except possibly temporarily for when all of GitHub Pages was down on Oct 22-23.

However, we are in the process of migrating to our own domain and currently set our GitHub page to redirect people over there automatically after a few seconds. I would like the js.org subdomain to be active for some more time to make sure most people have the new link. Is this acceptable under your "reasonable content" policy?

**Comment by MattIPv4** [comment]
@ByteCommander at the time the dead list was curated the domain returned a 404 multiple times to a scraper and to a human. Other sites on GitHub resolved fine, so not sure what the problem was.

If you’d like to keep the domain, please reply to the main cleanup issue: https://github.com/js-org/js.org/issues/2455 with a message in the format specified :)

**Comment by ByteCommander** [comment]
Alright, I have done so, therefore I'll close this issue for now: https://github.com/js-org/js.org/issues/2455#issuecomment-434597307
